#ifndef errors_h
#define errors_h

  #define NO_ERRORS 0
  #define INPUT_MAX_LENGTH_ERROR 1
  #define INVALID_COMMAND_ERROR 2
  #define INSUFICIENT_VALUES_ERROR 3
  #define UNDEFINED 4
  #define DOMAIN_BETWEEN_ERROR 5
  #define DOMAIN_LOG_ERROR 6
  #define DOMAIN_TAN_ERROR 7
  #define DIVIDED_BY_ZERO_ERROR 8
  #define NEGATIVE_NUMBER_ERROR 9
  #define DECIMAL_ERROR 10
  #define ZERO_ERROR 11
  #define INSUFICIENT_VALUES_IN_MEMORY_ERROR 12

#endif
